"""Implementa modelo Many-to-Many para treinos

Revision ID: 80d1f8323be1
Revises: 767fe38cdc1e
Create Date: 2025-09-29 08:46:01.961122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d1f8323be1'
down_revision = '767fe38cdc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('gif_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('treinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('dia', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treino_exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('repeticoes', sa.String(length=50), nullable=True),
    sa.Column('descanso_seg', sa.Integer(), nullable=True),
    sa.Column('peso', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treino_exercicio')
    op.drop_table('treinos')
    op.drop_table('exercicios')
    # ### end Alembic commands ###
