"""Add endereco to academia

Revision ID: f2ae917664e2
Revises: ea0f3fdd9a18
Create Date: 2025-11-28 11:57:37.355739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ae917664e2'
down_revision = 'ea0f3fdd9a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))

    with op.batch_alter_table('adm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['usuario_id'])
        batch_op.drop_constraint(batch_op.f('fk_adm_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('nivel_permissao')
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.alter_column('id_academia',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_instrutor',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['usuario_id'])
        batch_op.drop_constraint(batch_op.f('fk_aluno_usuario'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_aluno_instrutor'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'instrutor', ['id_instrutor'], ['id'])
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('exercicios', schema=None) as batch_op:
        batch_op.alter_column('grupo_muscular',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('instrutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cref', sa.String(length=20), nullable=True))
        batch_op.alter_column('id_academia',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['usuario_id'])
        batch_op.drop_constraint(batch_op.f('fk_instrutor_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('registro_itens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('registro_itens_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'registros_treino', ['registro_id'], ['id'])
        batch_op.drop_column('carga_kg')

    with op.batch_alter_table('registros_treino', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('tel',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('tel',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('registros_treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'concluido'"), nullable=True))

    with op.batch_alter_table('registro_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_kg', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('registro_itens_ibfk_1'), 'registros_treino', ['registro_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('instrutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_instrutor_usuario'), 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_academia',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('cref')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('exercicios', schema=None) as batch_op:
        batch_op.alter_column('grupo_muscular',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_aluno_instrutor'), 'instrutor', ['id_instrutor'], ['id_usuario'])
        batch_op.create_foreign_key(batch_op.f('fk_aluno_usuario'), 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_instrutor',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_academia',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('adm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nivel_permissao', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_adm_usuario'), 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('academia', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
